--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/guianginamo19/TagsUI
build-by-default: true
branches:
- master
projects:
  TagsUI:
    path: "" 
    icon: "IMG_20200729_134050.jpg"
...
