name: TagsUI
version: 1.0.0
main: Guin\tagsui\Main
api: 3.14.2
author: Guin
commands:
  tagsui:
    description: Open TagsUI
    
permissions:
  tags.knight:
    description: knight Tag
    default: op
  tags.warrior:
    description: warrior Tag
    default: op
  tags.armorer:
    description: armorer Tag
    default: op
  tags.archer:
    description: archer Tag
    default: op
  tags.wizard:
    description: wizard Tag
    default: op
  tags.queen:
    description: queen Tag
    default: op
  tags.king:
    description: king Tag
    default: op
